package lv.example.mogerstodolist;

import android.content.Context;
import android.database.DatabaseErrorHandler;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

public class TasksSQLiteHelper extends SQLiteOpenHelper {
    public static final String TABLE_TASKS = "tasks";
    public static final String COLUMN_ID = "id";
    public static final String COLUMN_PRIORITY = "priority";
    public static final String COLUMN_DATE = "date";
    public static final String COLUMN_TASK = "task";
    public static final String COLUMN_COMPLETED = "completed";

    public static final String DATABASE_NAME = "tasks.db";
    public static final int DATABASE_VERSION = 1;

//Database creation sql statement
    private static final String DATABASE_CREATE = "create table "
        +TABLE_TASKS + "("
        + COLUMN_ID + " integer primary key autoincrement, "
        + COLUMN_PRIORITY + " integer not null, "
        + COLUMN_DATE + " text not null, "
        + COLUMN_TASK + " text not null, "
        + COLUMN_COMPLETED + " integer not null);";
    private String OldVersion;


    public TasksSQLiteHelper(@Nullable Context context, @Nullable String name, @Nullable SQLiteDatabase.CursorFactory factory, int version) {
        super(context, name, factory, version);
    }

    public TasksSQLiteHelper(@Nullable Context context, @Nullable String name, @Nullable SQLiteDatabase.CursorFactory factory, int version, @Nullable DatabaseErrorHandler errorHandler) {
        super(context, name, factory, version, errorHandler);
    }

    public TasksSQLiteHelper(@Nullable Context context, @Nullable String name, int version, @NonNull SQLiteDatabase.OpenParams openParams) {
        super(context, name, version, openParams);
    }

    public TasksSQLiteHelper (Context context){
        super(context, DATABASE_NAME, null, DATABASE_VERSION);
        /* TO DO autogenerated constructor stub */

    }

    @Override
    public void onCreate(SQLiteDatabase db){
        db.execSQL(DATABASE_CREATE);
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {

    }


    public void onUpgrade(SQLiteDatabase db, int newVersion){
        Log.w(TasksSQLiteHelper.class.getName(),
                "Upgrading database from version " + OldVersion + " to "
        + newVersion + ", which will destroy all old data");

        db.execSQL("DROP TABLE IF EXISTS" + TABLE_TASKS);
        onCreate(db);
    }

}//end class
